<a href="https://colab.research.google.com/github/izabelmoreira/marketing-cloud/blob/main/DataScienceBootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import panda as pd

ModuleNotFoundError: ignored

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
d = [1,5,10]
Serie = pd.Series(data=d)
Serie

0     1
1     5
2    10
dtype: int64

In [ ]:
d = {'column1': [1,2,3], 'column2':[4,5,6]}
df = pd.DataFrame(data=d)
df

   column1  column2
0        1        4
1        2        5
2        3        6

In [ ]:
d = [(1,3), (2,4), (3,5)]
c = ["column1", "column2"]
df = pd.DataFrame(data = d, columns = c)
df

   column1  column2
0        1        3
1        2        4
2        3        5

In [8]:
world_data = pd.read_csv('https://raw.githubusercontent.com/PabloJMoreno/dataset/main/world-data-2023.csv', header = 0)

In [9]:
world_data

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [10]:
dataframe = world_data.copy()
serie = world_data('Abbreviation')

TypeError: ignored

In [11]:
dataframe = world_data.copy()
serie = world_data['Abbreviation']

In [12]:
dataframe

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [13]:
serie

0      AF
1      AL
2      DZ
3      AD
4      AO
       ..
190    VE
191    VN
192    YE
193    ZM
194    ZW
Name: Abbreviation, Length: 195, dtype: object

In [14]:
serie.dtype

dtype('O')

In [15]:
serie.index

RangeIndex(start=0, stop=195, step=1)

In [16]:
serie.size

195

In [17]:
sere.hasnans

NameError: ignored

In [18]:
serie.hasnans

True

In [19]:
serie.isunique

AttributeError: ignored

In [20]:
serie.is_unique

False

In [21]:
serie.name

'Abbreviation'

In [22]:
serie.ndim

1

In [24]:
dataframe.dtypes

Country                                       object
Density\n(P/Km2)                              object
Abbreviation                                  object
Agricultural Land( %)                         object
Land Area(Km2)                                object
Armed Forces size                             object
Birth Rate                                   float64
Calling Code                                 float64
Capital/Major City                            object
Co2-Emissions                                 object
CPI                                           object
CPI Change (%)                                object
Currency-Code                                 object
Fertility Rate                               float64
Forested Area (%)                             object
Gasoline Price                                object
GDP                                           object
Gross primary education enrollment (%)        object
Gross tertiary education enrollment (%)       object
Infant mortality                             float64
Largest city                                  object
Life expectancy                              float64
Maternal mortality ratio                     float64
Minimum wage                                  object
Official language                             object
Out of pocket health expenditure              object
Physicians per thousand                      float64
Population                                    object
Population: Labor force participation (%)     object
Tax revenue (%)                               object
Total tax rate                                object
Unemployment rate                             object
Urban_population                              object
Latitude                                     float64
Longitude                                    float64
dtype: object

In [25]:
dataframe.index

RangeIndex(start=0, stop=195, step=1)

In [26]:
dataframe.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

In [27]:
for column in dataframe.columns:
  print(column)

Country
Density
(P/Km2)
Abbreviation
Agricultural Land( %)
Land Area(Km2)
Armed Forces size
Birth Rate
Calling Code
Capital/Major City
Co2-Emissions
CPI
CPI Change (%)
Currency-Code
Fertility Rate
Forested Area (%)
Gasoline Price
GDP
Gross primary education enrollment (%)
Gross tertiary education enrollment (%)
Infant mortality
Largest city
Life expectancy
Maternal mortality ratio
Minimum wage
Official language
Out of pocket health expenditure
Physicians per thousand
Population
Population: Labor force participation (%)
Tax revenue (%)
Total tax rate
Unemployment rate
Urban_population
Latitude
Longitude

In [28]:
dataframe.shape

(195, 35)

In [29]:
dataframe.size

6825

In [30]:
serie.count()

188

In [32]:
serie.max

<bound method NDFrame._add_numeric_operations.<locals>.max of 0      AF
1      AL
2      DZ
3      AD
4      AO
       ..
190    VE
191    VN
192    YE
193    ZM
194    ZW
Name: Abbreviation, Length: 195, dtype: object>

In [33]:
br = world_data['Birth Rate']
br.max()

46.08

In [34]:
br.min()

5.9

In [35]:
br.sum()

3820.63

In [36]:
br.cumsum()

0        32.49
1        44.27
2        68.55
3        75.75
4       116.48
        ...
190    3706.56
191    3723.31
192    3753.76
193    3789.95
194    3820.63
Name: Birth Rate, Length: 195, dtype: float64

In [37]:
br.mean()

20.214973544973546

In [38]:
br.median()

17.95

In [39]:
br.std()

9.945773753600424

In [40]:
br.quantile(0.5)

17.95

In [41]:
br.quantile(0.25)

11.3

In [42]:
br.quantile(0.75)

28.75

In [43]:
br.describe()

count    189.000000
mean      20.214974
std        9.945774
min        5.900000
25%       11.300000
50%       17.950000
75%       28.750000
max       46.080000
Name: Birth Rate, dtype: float64

In [44]:
br.apply(np.log)

0      3.480932
1      2.466403
2      3.189653
3      1.974081
4      3.706965
         ...
190    2.883683
191    2.818398
192    3.416086
193    3.588783
194    3.423611
Name: Birth Rate, Length: 195, dtype: float64

In [45]:
br.sort_values()

113    5.9
162    6.4
149    6.8
3      7.2
83     7.3
      ...
73     NaN
120    NaN
128    NaN
133    NaN
181    NaN
Name: Birth Rate, Length: 195, dtype: float64

In [46]:
br.sort_values(ascending = False)

125    46.08
34     42.17
160    41.75
105    41.54
45     41.18
       ...
73       NaN
120      NaN
128      NaN
133      NaN
181      NaN
Name: Birth Rate, Length: 195, dtype: float64

In [47]:
br.sort_index()

0      32.49
1      11.78
2      24.28
3       7.20
4      40.73
       ...
190    17.88
191    16.75
192    30.45
193    36.19
194    30.68
Name: Birth Rate, Length: 195, dtype: float64

In [48]:
dataframe.count()

Country                                      195
Density\n(P/Km2)                             195
Abbreviation                                 188
Agricultural Land( %)                        188
Land Area(Km2)                               194
Armed Forces size                            171
Birth Rate                                   189
Calling Code                                 194
Capital/Major City                           192
Co2-Emissions                                188
CPI                                          178
CPI Change (%)                               179
Currency-Code                                180
Fertility Rate                               188
Forested Area (%)                            188
Gasoline Price                               175
GDP                                          193
Gross primary education enrollment (%)       188
Gross tertiary education enrollment (%)      183
Infant mortality                             189
Largest city                                 189
Life expectancy                              187
Maternal mortality ratio                     181
Minimum wage                                 150
Official language                            194
Out of pocket health expenditure             188
Physicians per thousand                      188
Population                                   194
Population: Labor force participation (%)    176
Tax revenue (%)                              169
Total tax rate                               183
Unemployment rate                            176
Urban_population                             190
Latitude                                     194
Longitude                                    194
dtype: int64

In [49]:
dataframe.max()

<ipython-input-49-1c47a5e5022e>:1: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.max()

Country                       Zimbabwe
Density\n(P/Km2)                    99
Birth Rate                       46.08
Calling Code                    1876.0
Fertility Rate                    6.91
Infant mortality                  84.5
Life expectancy                   85.4
Maternal mortality ratio        1150.0
Physicians per thousand           8.42
Latitude                     64.963051
Longitude                   178.065032
dtype: object

In [50]:
dataframe.min()

<ipython-input-50-fbab85aacb53>:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.min()

Country                     Afghanistan
Density\n(P/Km2)                  1,265
Birth Rate                          5.9
Calling Code                        1.0
Fertility Rate                     0.98
Infant mortality                    1.4
Life expectancy                    52.8
Maternal mortality ratio            2.0
Physicians per thousand            0.01
Latitude                     -40.900557
Longitude                   -175.198242
dtype: object

In [51]:
dataframe.sum()

<ipython-input-51-cdbfa00ac2df>:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.sum()

Country                     AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...
Density\n(P/Km2)            601051816426223171043109123392,2391,2656684738...
Birth Rate                                                            3820.63
Calling Code                                                          69946.0
Fertility Rate                                                         507.25
Infant mortality                                                       4031.9
Life expectancy                                                       13516.3
Maternal mortality ratio                                              29031.0
Physicians per thousand                                                345.89
Latitude                                                          3703.916186
Longitude                                                         3925.092291
dtype: object

In [52]:
dataframe.mean()

<ipython-input-52-ad2b37d7ca22>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.mean()

Birth Rate                   20.214974
Calling Code                360.546392
Fertility Rate                2.698138
Infant mortality             21.332804
Life expectancy              72.279679
Maternal mortality ratio    160.392265
Physicians per thousand       1.839840
Latitude                     19.092351
Longitude                    20.232434
dtype: float64

In [53]:
dataframe.median()

<ipython-input-53-7f7fa06dcf61>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.median()

Birth Rate                   17.950000
Calling Code                255.500000
Fertility Rate                2.245000
Infant mortality             14.000000
Life expectancy              73.200000
Maternal mortality ratio     53.000000
Physicians per thousand       1.460000
Latitude                     17.273849
Longitude                    20.972652
dtype: float64

In [54]:
dataframe.std()

<ipython-input-54-90bdd6cc73ba>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.std()

Birth Rate                    9.945774
Calling Code                323.236419
Fertility Rate                1.282267
Infant mortality             19.548058
Life expectancy               7.483661
Maternal mortality ratio    233.502024
Physicians per thousand       1.684261
Latitude                     23.961779
Longitude                    66.716110
dtype: float64

In [55]:
dataframe.quantile(0.5)

<ipython-input-55-92e0a2042ff6>:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.quantile(0.5)

Birth Rate                   17.950000
Calling Code                255.500000
Fertility Rate                2.245000
Infant mortality             14.000000
Life expectancy              73.200000
Maternal mortality ratio     53.000000
Physicians per thousand       1.460000
Latitude                     17.273849
Longitude                    20.972652
Name: 0.5, dtype: float64

In [56]:
dataframe.quantile(0.25)

<ipython-input-56-886a690579b6>:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.quantile(0.25)

Birth Rate                  11.300000
Calling Code                82.500000
Fertility Rate               1.705000
Infant mortality             6.000000
Life expectancy             67.000000
Maternal mortality ratio    13.000000
Physicians per thousand      0.332500
Latitude                     4.544175
Longitude                   -7.941496
Name: 0.25, dtype: float64

In [57]:
dataframe.quantile(0.75)

<ipython-input-57-45fed5d306d9>:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe.quantile(0.75)

Birth Rate                   28.750000
Calling Code                506.750000
Fertility Rate                3.597500
Infant mortality             32.700000
Life expectancy              77.500000
Maternal mortality ratio    186.000000
Physicians per thousand       2.935000
Latitude                     40.124603
Longitude                    48.281523
Name: 0.75, dtype: float64

In [58]:
dataframe.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [59]:
dataframe.tail()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [60]:
dataframe.head(10)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
5,Antigua and Barbuda,223,AG,20.50%,443,0,15.33,1.0,"St. John's, Saint John",557,...,24.30%,2.76,"97,118",NaN,16.50%,43.00%,NaN,"23,800",17.060816,-61.796428
6,Argentina,17,AR,54.30%,"2,780,400","105,000",17.02,54.0,Buenos Aires,"201,348",...,17.60%,3.96,"44,938,712",61.30%,10.10%,106.30%,9.79%,"41,339,571",-38.416097,-63.616672
7,Armenia,104,AM,58.90%,"29,743","49,000",13.99,374.0,Yerevan,"5,156",...,81.60%,4.40,"2,957,731",55.60%,20.90%,22.60%,16.99%,"1,869,848",40.069099,45.038189
8,Australia,3,AU,48.20%,"7,741,220","58,000",12.60,61.0,Canberra,"375,908",...,19.60%,3.68,"25,766,605",65.50%,23.00%,47.40%,5.27%,"21,844,756",-25.274398,133.775136
9,Austria,109,AT,32.40%,"83,871","21,000",9.70,43.0,Vienna,"61,448",...,17.90%,5.17,"8,877,067",60.70%,25.40%,51.40%,4.67%,"5,194,416",47.516231,14.550072

In [61]:
dataframe.rename({'Density\n(P/Km2)': 'Density'})

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [62]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    object
 1   Density
(P/Km2)                            195 non-null    object
 2   Abbreviation                               188 non-null    object
 3   Agricultural Land( %)                      188 non-null    object
 4   Land Area(Km2)                             194 non-null    object
 5   Armed Forces size                          171 non-null    object
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object
 9   Co2-Emissions                              188 non-null    object
 10  CPI                                        178 non-null    object
 11  CPI Change (%)                             179 non-null    object
 12  Currency-Code                              180 non-null    object
 13  Fertility Rate                             188 non-null    float64
 14  Forested Area (%)                          188 non-null    object
 15  Gasoline Price                             175 non-null    object
 16  GDP                                        193 non-null    object
 17  Gross primary education enrollment (%)     188 non-null    object
 18  Gross tertiary education enrollment (%)    183 non-null    object
 19  Infant mortality                           189 non-null    float64
 20  Largest city                               189 non-null    object
 21  Life expectancy                            187 non-null    float64
 22  Maternal mortality ratio                   181 non-null    float64
 23  Minimum wage                               150 non-null    object
 24  Official language                          194 non-null    object
 25  Out of pocket health expenditure           188 non-null    object
 26  Physicians per thousand                    188 non-null    float64
 27  Population                                 194 non-null    object
 28  Population: Labor force participation (%)  176 non-null    object
 29  Tax revenue (%)                            169 non-null    object
 30  Total tax rate                             183 non-null    object
 31  Unemployment rate                          176 non-null    object
 32  Urban_population                           190 non-null    object
 33  Latitude                                   194 non-null    float64
 34  Longitude                                  194 non-null    float64
dtypes: float64(9), object(26)
memory usage: 53.4+ KB

In [63]:
dataframe.describe()

,Birth Rate,Calling Code,Fertility Rate,Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Latitude,Longitude
count,189.000000,194.000000,188.000000,189.000000,187.000000,181.000000,188.000000,194.000000,194.000000
mean,20.214974,360.546392,2.698138,21.332804,72.279679,160.392265,1.839840,19.092351,20.232434
std,9.945774,323.236419,1.282267,19.548058,7.483661,233.502024,1.684261,23.961779,66.716110
min,5.900000,1.000000,0.980000,1.400000,52.800000,2.000000,0.010000,-40.900557,-175.198242
25%,11.300000,82.500000,1.705000,6.000000,67.000000,13.000000,0.332500,4.544175,-7.941496
50%,17.950000,255.500000,2.245000,14.000000,73.200000,53.000000,1.460000,17.273849,20.972652
75%,28.750000,506.750000,3.597500,32.700000,77.500000,186.000000,2.935000,40.124603,48.281523
max,46.080000,1876.000000,6.910000,84.500000,85.400000,1150.000000,8.420000,64.963051,178.065032

In [64]:
dataframe.describe(include = 'all')

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
count,195,195,188,188,194,171,189.000000,194.000000,192,188,...,188,188.000000,194,176,169,183,176,190,194.000000,194.000000
unique,195,137,188,168,194,105,NaN,NaN,192,184,...,160,NaN,194,145,119,156,164,190,NaN,NaN
top,Afghanistan,25,AF,17.40%,"652,230","2,000",NaN,NaN,Kabul,143,...,40.50%,NaN,"38,041,754",68.80%,19.50%,36.60%,4.59%,"9,797,273",NaN,NaN
freq,1,7,1,3,1,7,NaN,NaN,1,2,...,3,NaN,1,3,4,4,3,1,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,20.214974,360.546392,NaN,NaN,...,NaN,1.839840,NaN,NaN,NaN,NaN,NaN,NaN,19.092351,20.232434
std,NaN,NaN,NaN,NaN,NaN,NaN,9.945774,323.236419,NaN,NaN,...,NaN,1.684261,NaN,NaN,NaN,NaN,NaN,NaN,23.961779,66.716110
min,NaN,NaN,NaN,NaN,NaN,NaN,5.900000,1.000000,NaN,NaN,...,NaN,0.010000,NaN,NaN,NaN,NaN,NaN,NaN,-40.900557,-175.198242
25%,NaN,NaN,NaN,NaN,NaN,NaN,11.300000,82.500000,NaN,NaN,...,NaN,0.332500,NaN,NaN,NaN,NaN,NaN,NaN,4.544175,-7.941496
50%,NaN,NaN,NaN,NaN,NaN,NaN,17.950000,255.500000,NaN,NaN,...,NaN,1.460000,NaN,NaN,NaN,NaN,NaN,NaN,17.273849,20.972652
75%,NaN,NaN,NaN,NaN,NaN,NaN,28.750000,506.750000,NaN,NaN,...,NaN,2.935000,NaN,NaN,NaN,NaN,NaN,NaN,40.124603,48.281523
max,NaN,NaN,NaN,NaN,NaN,NaN,46.080000,1876.000000,NaN,NaN,...,NaN,8.420000,NaN,NaN,NaN,NaN,NaN,NaN,64.963051,178.065032

In [65]:
dataframe.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Country,195,195,Afghanistan,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Density\n(P/Km2),195,137,25,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abbreviation,188,188,AF,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Agricultural Land( %),188,168,17.40%,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Land Area(Km2),194,194,"652,230",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Armed Forces size,171,105,"2,000",7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Rate,189.0,NaN,NaN,NaN,20.214974,9.945774,5.9,11.3,17.95,28.75,46.08
Calling Code,194.0,NaN,NaN,NaN,360.546392,323.236419,1.0,82.5,255.5,506.75,1876.0
Capital/Major City,192,192,Kabul,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Co2-Emissions,188,184,143,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPI,178,175,110.62,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPI Change (%),179,86,2.80%,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Currency-Code,180,133,EUR,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fertility Rate,188.0,NaN,NaN,NaN,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91
Forested Area (%),188,161,43.10%,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gasoline Price,175,101,$0.71,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GDP,193,193,"$19,101,353,833",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross primary education enrollment (%),188,141,104.00%,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross tertiary education enrollment (%),183,171,10.20%,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Infant mortality,189.0,NaN,NaN,NaN,21.332804,19.548058,1.4,6.0,14.0,32.7,84.5
Largest city,189,188,S����,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Life expectancy,187.0,NaN,NaN,NaN,72.279679,7.483661,52.8,67.0,73.2,77.5,85.4
Maternal mortality ratio,181.0,NaN,NaN,NaN,160.392265,233.502024,2.0,13.0,53.0,186.0,1150.0
Minimum wage,150,114,$0.41,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Official language,194,77,English,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Out of pocket health expenditure,188,160,40.50%,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Physicians per thousand,188.0,NaN,NaN,NaN,1.83984,1.684261,0.01,0.3325,1.46,2.935,8.42
Population,194,194,"38,041,754",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population: Labor force participation (%),176,145,68.80%,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tax revenue (%),169,119,19.50%,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total tax rate,183,156,36.60%,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unemployment rate,176,164,4.59%,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Urban_population,190,190,"9,797,273",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,194.0,NaN,NaN,NaN,19.092351,23.961779,-40.900557,4.544175,17.273849,40.124603,64.963051
Longitude,194.0,NaN,NaN,NaN,20.232434,66.71611,-175.198242,-7.941496,20.972652,48.281523,178.065032

In [66]:
dataframe.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [67]:
subset_1 = dataframe[['Country', 'Abbreviation']]

In [68]:
subset_1.head()

       Country Abbreviation
0  Afghanistan           AF
1      Albania           AL
2      Algeria           DZ
3      Andorra           AD
4       Angola           AO

In [69]:
subset_2 = dataframe.iloc[0:2]
subset_2.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331

In [70]:
subset_3 = dataframe.iloc[:,1:3]

In [71]:
subset_3.head()

  Density\n(P/Km2) Abbreviation
0               60           AF
1              105           AL
2               18           DZ
3              164           AD
4               26           AO

In [72]:
subset_4 = dataframe.iloc[0:100, 2:-1]
subset_4.head()

,Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),...,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude
0,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110
1,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,...,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332
2,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,...,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886
3,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,...,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285
4,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,...,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692

In [74]:
subset_5 = dataframe[dataframe['Birth Rate'] >=25.2]
subset_5.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
18,Benin,108,BJ,33.30%,"112,622","12,000",36.22,229.0,Porto-Novo,"6,476",...,40.50%,0.08,"11,801,151",70.90%,10.80%,48.90%,2.23%,"5,648,149",9.307690,2.315834
26,Burkina Faso,76,BF,44.20%,"274,200","11,000",37.93,226.0,Ouagadougou,"3,418",...,36.10%,0.08,"20,321,378",66.40%,15.00%,41.30%,6.26%,"6,092,349",12.238333,-1.561593
27,Burundi,463,BI,79.20%,"27,830","31,000",39.01,257.0,Bujumbura,495,...,19.10%,0.10,"11,530,580",79.20%,13.60%,41.20%,1.43%,"1,541,177",-3.373056,29.918886

In [76]:
subset_6 = dataframe[dataframe['Abbreviation'] == "PA"]

In [77]:
subset__6.head()

NameError: ignored

In [78]:
subset_6.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
134,Panama,58,PA,30.40%,"75,420","26,000",18.98,507.0,Panama City,"10,715",...,30.50%,1.57,"4,246,439",66.60%,NaN,37.20%,3.90%,"2,890,084",8.537981,-80.782127

In [81]:
subset_7 = dataframe.loc[(dataframe['Fertility Rate'] >= 6) & (dataframe['Birth Rate'] > 20)]
subset_7.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
125,Niger,19,NE,36.10%,"1,267,000","10,000",46.08,227.0,Niamey,"2,017",...,52.30%,0.04,"23,310,715",72.00%,11.80%,47.20%,0.47%,"3,850,231",17.607789,8.081666
160,Somalia,25,SO,70.30%,"637,657","20,000",41.75,252.0,Mogadishu,645,...,NaN,0.02,"15,442,905",47.40%,0.00%,NaN,11.35%,"7,034,861",5.152149,46.199616

In [82]:
dataframe.sort_values(by = ['Birth Rate'])

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
113,Monaco,"26,337",MC,NaN,2,NaN,5.9,377.0,Monaco City,NaN,...,6.10%,6.56,"38,964",NaN,NaN,NaN,NaN,"38,964",43.738418,7.424616
162,South Korea,527,KR,17.40%,"99,720","634,000",6.4,82.0,Seoul,"620,302",...,36.80%,2.36,"51,709,098",63.00%,15.60%,33.20%,4.15%,"42,106,719",35.907757,127.766922
149,San Marino,566,SM,16.70%,61,NaN,6.8,378.0,City of San Marino,NaN,...,18.30%,6.11,"33,860",NaN,18.10%,36.20%,NaN,"32,969",43.942360,12.457777
3,Andorra,164,AD,40.00%,468,NaN,7.2,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
83,Italy,206,IT,43.20%,"301,340","347,000",7.3,39.0,Rome,"320,411",...,22.80%,3.98,"60,297,396",49.60%,24.30%,59.10%,9.89%,"42,651,966",41.871940,12.567380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Vatican City,"2,003",NaN,NaN,0,NaN,NaN,379.0,Vatican City,NaN,...,NaN,NaN,836,NaN,NaN,NaN,NaN,NaN,41.902916,12.453389
120,Nauru,541,NR,NaN,21,NaN,NaN,674.0,Yaren District,NaN,...,NaN,NaN,"10,084",NaN,NaN,NaN,NaN,NaN,-0.522778,166.931503
128,North Macedonia,83,NaN,NaN,"25,713",NaN,NaN,389.0,Skopje,NaN,...,35.60%,NaN,"1,836,713",NaN,NaN,NaN,NaN,NaN,41.608635,21.745275
133,Palestinian National Authority,847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.952162,35.233154
181,Tuvalu,393,TV,60.00%,26,NaN,NaN,688.0,Funafuti,11,...,0.70%,0.92,"11,646",NaN,NaN,NaN,NaN,"7,362",-7.109535,177.649330

In [83]:
dataframe.sort_values(by = ['Birth Rate'], ascending = False)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
125,Niger,19,NE,36.10%,"1,267,000","10,000",46.08,227.0,Niamey,"2,017",...,52.30%,0.04,"23,310,715",72.00%,11.80%,47.20%,0.47%,"3,850,231",17.607789,8.081666
34,Chad,13,TD,39.70%,"1,284,000","35,000",42.17,235.0,N'Djamena,"1,016",...,56.40%,0.04,"15,946,876",70.70%,NaN,63.50%,1.89%,"3,712,273",15.454166,18.732207
160,Somalia,25,SO,70.30%,"637,657","20,000",41.75,252.0,Mogadishu,645,...,NaN,0.02,"15,442,905",47.40%,0.00%,NaN,11.35%,"7,034,861",5.152149,46.199616
105,Mali,17,ML,33.80%,"1,240,192","18,000",41.54,223.0,Bamako,"3,179",...,46.30%,0.13,"19,658,031",70.80%,11.60%,54.50%,7.22%,"8,479,688",17.570692,-3.996166
45,Democratic Republic of the Congo,40,CD,11.60%,"2,344,858","134,000",41.18,243.0,Kinshasa,"2,021",...,37.40%,0.07,"86,790,567",63.50%,10.70%,50.70%,4.24%,"39,095,679",-4.038333,21.758664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Vatican City,"2,003",NaN,NaN,0,NaN,NaN,379.0,Vatican City,NaN,...,NaN,NaN,836,NaN,NaN,NaN,NaN,NaN,41.902916,12.453389
120,Nauru,541,NR,NaN,21,NaN,NaN,674.0,Yaren District,NaN,...,NaN,NaN,"10,084",NaN,NaN,NaN,NaN,NaN,-0.522778,166.931503
128,North Macedonia,83,NaN,NaN,"25,713",NaN,NaN,389.0,Skopje,NaN,...,35.60%,NaN,"1,836,713",NaN,NaN,NaN,NaN,NaN,41.608635,21.745275
133,Palestinian National Authority,847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.952162,35.233154
181,Tuvalu,393,TV,60.00%,26,NaN,NaN,688.0,Funafuti,11,...,0.70%,0.92,"11,646",NaN,NaN,NaN,NaN,"7,362",-7.109535,177.649330

In [84]:
# drop 1 column
dataframe.drop(columns = 'Birth Rate')
# drop multiple columns
dataframe.drop(columns = ['Abbreviation', 'Birth Rate'])

,Country,Density\n(P/Km2),Agricultural Land( %),Land Area(Km2),Armed Forces size,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,58.10%,"652,230","323,000",93.0,Kabul,"8,672",149.9,2.30%,...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,43.10%,"28,748","9,000",355.0,Tirana,"4,536",119.05,1.40%,...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,17.40%,"2,381,741","317,000",213.0,Algiers,"150,006",151.36,2.00%,...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,40.00%,468,NaN,376.0,Andorra la Vella,469,NaN,NaN,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,47.50%,"1,246,700","117,000",244.0,Luanda,"34,693",261.73,17.10%,...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,24.50%,"912,050","343,000",58.0,Caracas,"164,175","2,740.27",254.90%,...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,39.30%,"331,210","522,000",84.0,Hanoi,"192,668",163.52,2.80%,...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,44.60%,"527,968","40,000",967.0,Sanaa,"10,609",157.58,8.10%,...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,32.10%,"752,618","16,000",260.0,Lusaka,"5,141",212.31,9.20%,...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,41.90%,"390,757","51,000",263.0,Harare,"10,983",105.51,0.90%,...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [85]:
# select specific rows by index
dataframe.drop([0,1,4,7])

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
5,Antigua and Barbuda,223,AG,20.50%,443,0,15.33,1.0,"St. John's, Saint John",557,...,24.30%,2.76,"97,118",NaN,16.50%,43.00%,NaN,"23,800",17.060816,-61.796428
6,Argentina,17,AR,54.30%,"2,780,400","105,000",17.02,54.0,Buenos Aires,"201,348",...,17.60%,3.96,"44,938,712",61.30%,10.10%,106.30%,9.79%,"41,339,571",-38.416097,-63.616672
8,Australia,3,AU,48.20%,"7,741,220","58,000",12.60,61.0,Canberra,"375,908",...,19.60%,3.68,"25,766,605",65.50%,23.00%,47.40%,5.27%,"21,844,756",-25.274398,133.775136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [86]:
# check the shape of dataframe
dataframe.shape

(195, 35)

In [87]:
# check if there is any duplicated rows, store it in a new dataframe and show the duplicated rows

duplicated = dataframe[dataframe.duplicated() == True]
duplicated
# eliminate duplicate values and save it in another dataframe
# always keep the original source
dataframe_unique = dataframe.drop_duplicates()

In [88]:
# validate the shape of dataframe after removing duplicates
dataframe_unique.shape
# clone dataframe in a new object
df = world_data.copy()

In [89]:
dataframe.shape
# remove rows with NA or null values
dataframe = dataframe.dropna(axis = 0, how = "any")
dataframe.shape

(110, 35)

In [90]:
df_1 = pd.read_csv('https://raw.githubusercontent.com/PabloJMoreno/dataset/main/MSFT.csv', header = 0)
df_1
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1258 non-null   object
 1   Open       1258 non-null   float64
 2   High       1258 non-null   float64
 3   Low        1258 non-null   float64
 4   Close      1258 non-null   float64
 5   Adj Close  1258 non-null   float64
 6   Volume     1258 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 68.9+ KB

In [91]:
df_1['Date'] = pd.to_datetime(df_1['Date'])
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1258 non-null   datetime64[ns]
 1   Open       1258 non-null   float64
 2   High       1258 non-null   float64
 3   Low        1258 non-null   float64
 4   Close      1258 non-null   float64
 5   Adj Close  1258 non-null   float64
 6   Volume     1258 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 68.9 KB

In [92]:
# let's create a new dataframe object as we are going to make changes, so we always preserve the original dataset
df_time = df_1[['Date', 'Close']]
df_time.head()
df_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1258 non-null   datetime64[ns]
 1   Close   1258 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.8 KB

In [93]:
# all those transformation are possible because column 'Date' is now as date format
# we will create multiple new columns with the components of each date per row

df_time['only_date'] = df_time['Date'].dt.date
df_time['time'] = df_time['Date'].dt.time
df_time['y'] = df_time['Date'].dt.year
df_time['q'] = df_time['Date'].dt.quarter
df_time['m'] = df_time['Date'].dt.month
df_time['d'] = df_time['Date'].dt.day
df_time['h'] = df_time['Date'].dt.hour
df_time['min'] = df_time['Date'].dt.minute
df_time['sec'] = df_time['Date'].dt.second
df_time['woy'] = df_time['Date'].dt.weekofyear
df_time['dow'] = df_time['Date'].dt.weekday
df_time['doy'] = df_time['Date'].dt.dayofyear
df_time['fdom'] = df_time['Date'].dt.is_month_start
df_time['ldom'] = df_time['Date'].dt.is_month_end
df_time['fdoq'] = df_time['Date'].dt.is_quarter_start
df_time['ldoq'] = df_time['Date'].dt.is_quarter_end
df_time['fdoy'] = df_time['Date'].dt.is_year_start
df_time['ldoy'] = df_time['Date'].dt.is_year_end
df_time['d_m'] = df_time['Date'].dt.daysinmonth
df_time['d_n'] = df_time['Date'].dt.day_name()
df_time['m_n'] = df_time['Date'].dt.month_name()

<ipython-input-93-d1dd60f71d36>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_time['only_date'] = df_time['Date'].dt.date
<ipython-input-93-d1dd60f71d36>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_time['time'] = df_time['Date'].dt.time
<ipython-input-93-d1dd60f71d36>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_time['y'] = df_time['Date'].dt.year
<ipython-input-93-d1dd60f71d36>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_time['q'] = df_time['Date'].dt.quarter
<ipython-input-93-d1dd60f71d36>:13: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  df_time['woy'] = df_time['Date'].dt.weekofyear

In [94]:
# Let's review the result of the transformed dataframe
df_time

,Date,Close,only_date,time,y,q,m,d,h,min,...,doy,fdom,ldom,fdoq,ldoq,fdoy,ldoy,d_m,d_n,m_n
0,2016-03-07,51.029999,2016-03-07,00:00:00,2016,1,3,7,0,0,...,67,False,False,False,False,False,False,31,Monday,March
1,2016-03-08,51.650002,2016-03-08,00:00:00,2016,1,3,8,0,0,...,68,False,False,False,False,False,False,31,Tuesday,March
2,2016-03-09,52.840000,2016-03-09,00:00:00,2016,1,3,9,0,0,...,69,False,False,False,False,False,False,31,Wednesday,March
3,2016-03-10,52.049999,2016-03-10,00:00:00,2016,1,3,10,0,0,...,70,False,False,False,False,False,False,31,Thursday,March
4,2016-03-11,53.070000,2016-03-11,00:00:00,2016,1,3,11,0,0,...,71,False,False,False,False,False,False,31,Friday,March
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253,2021-02-26,232.380005,2021-02-26,00:00:00,2021,1,2,26,0,0,...,57,False,False,False,False,False,False,28,Friday,February
1254,2021-03-01,236.940002,2021-03-01,00:00:00,2021,1,3,1,0,0,...,60,True,False,False,False,False,False,31,Monday,March
1255,2021-03-02,233.869995,2021-03-02,00:00:00,2021,1,3,2,0,0,...,61,False,False,False,False,False,False,31,Tuesday,March
1256,2021-03-03,227.559998,2021-03-03,00:00:00,2021,1,3,3,0,0,...,62,False,False,False,False,False,False,31,Wednesday,March
1257,2021-03-04,226.729996,2021-03-04,00:00:00,2021,1,3,4,0,0,...,63,False,False,False,False,False,False,31,Thursday,March

In [95]:
df1 = pd.DataFrame([[100, 200], [300, 400]], columns=["columna 1", "columna 2"])
df1
df2 = pd.DataFrame([[500, 600], [700, 800]], columns=["columna 1", "columna 2"])
df2
df_appended = df1.append(df2)
df_appended

<ipython-input-95-58a3db004176>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_appended = df1.append(df2)

   columna 1  columna 2
0        100        200
1        300        400
0        500        600
1        700        800

In [96]:
df_appended2 = df1.append(df2, ignore_index=True)
df_appended2

<ipython-input-96-d211d7b791ed>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_appended2 = df1.append(df2, ignore_index=True)

   columna 1  columna 2
0        100        200
1        300        400
2        500        600
3        700        800

In [97]:
df3 = pd.DataFrame([[100, 200], [300, 400]], columns=["columna 1", "columna 2"])
df3

   columna 1  columna 2
0        100        200
1        300        400

In [98]:
df4 = pd.DataFrame([[500, 600], [700, 800]], columns=["columna 3", "columna 4"])
df4

   columna 3  columna 4
0        500        600
1        700        800

In [99]:
df_appended3 = df3.append(df4)
df_appended3

<ipython-input-99-f0d27b1fddb1>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_appended3 = df3.append(df4)

   columna 1  columna 2  columna 3  columna 4
0      100.0      200.0        NaN        NaN
1      300.0      400.0        NaN        NaN
0        NaN        NaN      500.0      600.0
1        NaN        NaN      700.0      800.0

In [100]:
df5 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])
df5

  letter  number
0      a       1
1      b       2

In [101]:
df6 = pd.DataFrame([['c', 3], ['d', 4]],

                   columns=['letter', 'number'])
df6

  letter  number
0      c       3
1      d       4

In [102]:
pd.concat([df5, df6])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [103]:
pd.concat([df5, df6], axis = 1)

  letter  number letter  number
0      a       1      c       3
1      b       2      d       4

In [104]:
df_left = pd.DataFrame(
    {"cliente": ["Carlos", "Luis", "Maria", "Susana", "Camila"],
     "region": ["Norte", "Norte", "Sur", "Sur", "Sur"]})
df_left
df_right = pd.DataFrame(
    {"cliente": ["Carlos", "Luis", "Maria", "Susana", "Pedro"],
     "compras": [1500, 300, 3000, 2000, 500]})
df_right

  cliente  compras
0  Carlos     1500
1    Luis      300
2   Maria     3000
3  Susana     2000
4   Pedro      500

In [105]:
pd.merge(df_left, df_right, how = "left", on = "cliente")

  cliente region  compras
0  Carlos  Norte   1500.0
1    Luis  Norte    300.0
2   Maria    Sur   3000.0
3  Susana    Sur   2000.0
4  Camila    Sur      NaN

In [106]:
pd.merge(df_left, df_right, how = "right", on = "cliente")

  cliente region  compras
0  Carlos  Norte     1500
1    Luis  Norte      300
2   Maria    Sur     3000
3  Susana    Sur     2000
4   Pedro    NaN      500

In [107]:
pd.merge(df_left, df_right, how = "outer", on = "cliente")

  cliente region  compras
0  Carlos  Norte   1500.0
1    Luis  Norte    300.0
2   Maria    Sur   3000.0
3  Susana    Sur   2000.0
4  Camila    Sur      NaN
5   Pedro    NaN    500.0

In [108]:
pd.merge(df_left, df_right, how = "inner", on = "cliente")

  cliente region  compras
0  Carlos  Norte     1500
1    Luis  Norte      300
2   Maria    Sur     3000
3  Susana    Sur     2000

In [109]:
data = pd.read_csv('https://raw.githubusercontent.com/PabloJMoreno/dataset/main/Credit_Rating.csv', header = 0)
data

,Unnamed: 0,company_reg_number,credit_report_agency,credit_report_date,credit_report_model,credit_report_requests_to_view_last_five_years,credit_report_total_indebtedness,liens_filed_and_open,liens_closed_last_five_years,missed_and_late_payments_last_five_years,filed_court_cases_last_five_years,payment_index,credit_report_negative_items,credit_report_good_standing_items,business_failure_score,credit_report_credit_score,ratio_debt_to_revenue
0,0,20000000,Experian,2021-11-23,FICO 8,6,7548.00,0,1,0,0,2,1,4,63,765,0.013964
1,1,20000001,Equifax,2021-01-29,FICO 8,5,28100.00,0,0,0,0,21,1,1,59,676,0.121491
2,2,20000002,Equifax,2021-04-13,FICO 8,6,15631.00,0,1,0,0,16,1,4,53,663,0.076898
3,3,20000003,Equifax,2021-09-25,FICO 4,3,0.00,0,0,0,0,2,0,3,93,0,0.000000
4,4,20000004,Equifax,2021-08-13,FICO 9,0,75605.28,0,0,0,0,17,0,4,81,773,0.193195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,895,20000995,TransUnion,2021-03-03,FICO 9,0,0.00,0,1,3,0,16,5,0,47,736,0.000000
896,896,20000996,Experian,2021-03-19,FICO 9,7,13460.00,0,0,7,0,86,7,3,0,584,0.063807
897,897,20000997,Experian,2021-11-07,FICO 8,8,53532.56,0,0,0,1,9,1,4,58,653,0.357946
898,898,20000998,Experian,2020-12-09,FICO 8,0,50948.00,0,0,0,0,1,0,2,77,0,0.125415
899,899,20000999,Experian,2020-12-21,FICO 5,2,101936.55,0,0,1,0,4,6,3,5,509,0.260533

In [110]:
# let's create an aggregated table by 'credit_report_agency', using the `.mean()` as aggregation criteria. Only numeric values will be stored
# it is possible to use .sum() or .mean() or .max() or .min()
data_groupby = data.groupby(['credit_report_agency']).mean()

<ipython-input-110-e630b793c14c>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data_groupby = data.groupby(['credit_report_agency']).mean()

In [111]:
# let's display the aggregated data
data_groupby

,Unnamed: 0,company_reg_number,credit_report_requests_to_view_last_five_years,credit_report_total_indebtedness,liens_filed_and_open,liens_closed_last_five_years,missed_and_late_payments_last_five_years,filed_court_cases_last_five_years,payment_index,credit_report_negative_items,credit_report_good_standing_items,business_failure_score,credit_report_credit_score,ratio_debt_to_revenue
credit_report_agency,,,,,,,,,,,,,,
Equifax,458.565359,2.000051e+07,4.016340,73766.797320,0.003268,0.241830,1.535948,0.104575,23.643791,2.869281,2.614379,51.758170,596.611111,0.145044
Experian,442.020548,2.000049e+07,4.126712,77905.883699,0.003425,0.232877,1.606164,0.147260,23.113014,3.065068,2.571918,52.839041,590.958904,0.127239
TransUnion,447.546358,2.000049e+07,3.913907,81394.008113,0.013245,0.205298,1.539735,0.122517,23.155629,2.963576,2.556291,50.506623,606.307947,0.147160

In [112]:
# aggregating by one column

data_groupby2 = data.groupby(['credit_report_agency'])['credit_report_total_indebtedness'].mean()

In [113]:
data_groupby2

credit_report_agency
Equifax       73766.797320
Experian      77905.883699
TransUnion    81394.008113
Name: credit_report_total_indebtedness, dtype: float64

In [114]:
data_groupby3 = data.groupby(['credit_report_agency', 'credit_report_model']).mean()
data_groupby3

<ipython-input-114-0a68d3e7ecc3>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data_groupby3 = data.groupby(['credit_report_agency', 'credit_report_model']).mean()

                                          Unnamed: 0  company_reg_number  \
credit_report_agency credit_report_model
Equifax              FICO 2               437.000000        2.000048e+07
                     FICO 4               451.941176        2.000050e+07
                     FICO 5               488.127660        2.000054e+07
                     FICO 8               455.870504        2.000050e+07
                     FICO 9               427.000000        2.000047e+07
                     VantageScore         469.023810        2.000052e+07
Experian             FICO 2               413.368421        2.000046e+07
                     FICO 4               447.029412        2.000049e+07
                     FICO 5               445.162162        2.000049e+07
                     FICO 8               444.468966        2.000049e+07
                     FICO 9               444.060606        2.000049e+07
                     VantageScore         435.166667        2.000048e+07
TransUnion           FICO 2               379.500000        2.000042e+07
                     FICO 4               400.838710        2.000044e+07
                     FICO 5               389.826923        2.000043e+07
                     FICO 8               480.711268        2.000053e+07
                     FICO 9               445.575758        2.000049e+07
                     VantageScore         479.464286        2.000053e+07

                                          credit_report_requests_to_view_last_five_years  \
credit_report_agency credit_report_model
Equifax              FICO 2                                                     3.625000
                     FICO 4                                                     4.588235
                     FICO 5                                                     4.489362
                     FICO 8                                                     3.892086
                     FICO 9                                                     3.464286
                     VantageScore                                               3.952381
Experian             FICO 2                                                     4.736842
                     FICO 4                                                     3.529412
                     FICO 5                                                     4.054054
                     FICO 8                                                     4.055172
                     FICO 9                                                     4.666667
                     VantageScore                                               4.291667
TransUnion           FICO 2                                                     3.312500
                     FICO 4                                                     3.258065
                     FICO 5                                                     3.865385
                     FICO 8                                                     4.366197
                     FICO 9                                                     3.515152
                     VantageScore                                               3.250000

                                          credit_report_total_indebtedness  \
credit_report_agency credit_report_model
Equifax              FICO 2                                   74311.944375
                     FICO 4                                  100545.548529
                     FICO 5                                   74092.973191
                     FICO 8                                   73931.955755
                     FICO 9                                   36998.909286
                     VantageScore                             75481.408810
Experian             FICO 2                                  114464.643158
                     FICO 4                                   69203.926176
                     FICO 5                                   58913.068919
                     FICO 8                                   69651.297172
                     FICO 9                                   83704.846667
                     VantageScore                            132469.781250
TransUnion           FICO 2                                   52341.321250
                     FICO 4                                  108913.558710
                     FICO 5                                   88504.981154
                     FICO 8                                   81236.374930
                     FICO 9                                   58500.832727
                     VantageScore                             82102.044643

                                          liens_filed_and_open  \
credit_report_agency credit_report_model
Equifax              FICO 2                           0.000000
                     FICO 4                           0.000000
                     FICO 5                           0.000000
                     FICO 8                           0.007194
                     FICO 9                           0.000000
                     VantageScore                     0.000000
Experian             FICO 2                           0.000000
                     FICO 4                           0.000000
                     FICO 5                           0.000000
                     FICO 8                           0.000000
                     FICO 9                           0.030303
                     VantageScore                     0.000000
TransUnion           FICO 2                           0.000000
                     FICO 4                           0.000000
                     FICO 5                           0.019231
                     FICO 8                           0.014085
                     FICO 9                           0.000000
                     VantageScore                     0.035714

                                          liens_closed_last_five_years  \
credit_report_agency credit_report_model
Equifax              FICO 2                                   0.375000
                     FICO 4                                   0.323529
                     FICO 5                                   0.234043
                     FICO 8                                   0.208633
                     FICO 9                                   0.250000
                     VantageScore                             0.238095
Experian             FICO 2                                   0.210526
                     FICO 4                                   0.235294
                     FICO 5                                   0.162162
                     FICO 8                                   0.248276
                     FICO 9                                   0.242424
                     VantageScore                             0.250000
TransUnion           FICO 2                                   0.125000
                     FICO 4                                   0.096774
                     FICO 5                                   0.288462
                     FICO 8                                   0.211268
                     FICO 9                                   0.181818
                     VantageScore                             0.214286

                                          missed_and_late_payments_last_five_years  \
credit_report_agency credit_report_model
Equifax              FICO 2                                               2.187500
                     FICO 4                                               1.470588
                     FICO 5                                               2.085106
                     FICO 8                                               1.366906
                     FICO 9                                               1.285714
                     VantageScore                                         1.452381
Experian             FICO 2                                               2.000000
                     FICO 4                                               1.558824
                     FICO 5                                               1.972973
                     FICO 8                                               1.386207
                     FICO 9                                               1.787879
                     VantageScore                                         1.875000
TransUnion           FICO 2                                               1.250000
                     FICO 4                                               0.709677
                     FICO 5                                               1.769231
                     FICO 8                                               1.788732
                     FICO 9                                               1.212121
                     VantageScore                                         1.321429

                                          filed_court_cases_last_five_years  \
credit_report_agency credit_report_model
Equifax              FICO 2                                        0.187500
                     FICO 4                                        0.235294
                     FICO 5                                        0.085106
                     FICO 8                                        0.086331
                     FICO 9                                        0.035714
                     VantageScore                                  0.095238
Experian             FICO 2                                        0.157895
                     FICO 4                                        0.176471
                     FICO 5                                        0.135135
                     FICO 8                                        0.144828
                     FICO 9                                        0.121212
                     VantageScore                                  0.166667
TransUnion           FICO 2                                        0.250000
                     FICO 4                                        0.161290
                     FICO 5                                        0.115385
                     FICO 8                                        0.112676
                     FICO 9                                        0.060606
                     VantageScore                                  0.142857

                                          payment_index  \
credit_report_agency credit_report_model
Equifax              FICO 2                   27.125000
                     FICO 4                   24.647059
                     FICO 5                   25.063830
                     FICO 8                   23.179856
                     FICO 9                   22.000000
                     VantageScore             22.547619
Experian             FICO 2                   23.789474
                     FICO 4                   18.058824
                     FICO 5                   28.000000
                     FICO 8                   22.620690
                     FICO 9                   24.878788
                     VantageScore             22.750000
TransUnion           FICO 2                   21.812500
                     FICO 4                   19.161290
                     FICO 5                   28.942308
                     FICO 8                   23.598592
                     FICO 9                   19.727273
                     VantageScore             19.392857

                                          credit_report_negative_items  \
credit_report_agency credit_report_model
Equifax              FICO 2                                   4.000000
                     FICO 4                                   2.647059
                     FICO 5                                   3.425532
                     FICO 8                                   2.582734
                     FICO 9                                   3.000000
                     VantageScore                             2.857143
Experian             FICO 2                                   3.105263
                     FICO 4                                   3.411765
                     FICO 5                                   3.162162
                     FICO 8                                   2.882759
                     FICO 9                                   3.121212
                     VantageScore                             3.416667
TransUnion           FICO 2                                   3.125000
                     FICO 4                                   2.096774
                     FICO 5                                   3.019231
                     FICO 8                                   3.338028
                     FICO 9                                   2.272727
                     VantageScore                             2.642857

                                          credit_report_good_standing_items  \
credit_report_agency credit_report_model
Equifax              FICO 2                                        2.312500
                     FICO 4                                        2.147059
                     FICO 5                                        2.893617
                     FICO 8                                        2.712230
                     FICO 9                                        2.535714
                     VantageScore                                  2.523810
Experian             FICO 2                                        3.000000
                     FICO 4                                        2.529412
                     FICO 5                                        2.270270
                     FICO 8                                        2.503448
                     FICO 9                                        2.575758
                     VantageScore                                  3.166667
TransUnion           FICO 2                                        2.625000
                     FICO 4                                        2.193548
                     FICO 5                                        2.576923
                     FICO 8                                        2.647887
                     FICO 9                                        2.272727
                     VantageScore                                  2.750000

                                          business_failure_score  \
credit_report_agency credit_report_model
Equifax              FICO 2                            48.187500
                     FICO 4                            56.235294
                     FICO 5                            53.936170
                     FICO 8                            50.971223
                     FICO 9                            49.892857
                     VantageScore                      50.904762
Experian             FICO 2                            58.789474
                     FICO 4                            52.382353
                     FICO 5                            55.702703
                     FICO 8                            51.186207
                     FICO 9                            48.818182
                     VantageScore                      59.875000
TransUnion           FICO 2                            48.750000
                     FICO 4                            52.838710
                     FICO 5                            50.923077
                     FICO 8                            50.528169
                     FICO 9                            47.606061
                     VantageScore                      51.464286

                                          credit_report_credit_score  \
credit_report_agency credit_report_model
Equifax              FICO 2                               586.500000
                     FICO 4                               614.235294
                     FICO 5                               534.106383
                     FICO 8                               601.532374
                     FICO 9                               609.500000
                     VantageScore                         631.261905
Experian             FICO 2                               662.578947
                     FICO 4                               489.323529
                     FICO 5                               547.324324
                     FICO 8                               594.675862
                     FICO 9                               635.969697
                     VantageScore                         661.166667
TransUnion           FICO 2                               587.312500
                     FICO 4                               657.193548
                     FICO 5                               537.865385
                     FICO 8                               619.922535
                     FICO 9                               620.121212
                     VantageScore                         602.607143

                                          ratio_debt_to_revenue
credit_report_agency credit_report_model
Equifax              FICO 2                            0.126071
                     FICO 4                            0.168855
                     FICO 5                            0.160526
                     FICO 8                            0.143598
                     FICO 9                            0.124059
                     VantageScore                      0.134451
Experian             FICO 2                            0.139335
                     FICO 4                            0.159273
                     FICO 5                            0.100041
                     FICO 8                            0.124969
                     FICO 9                            0.122291
                     VantageScore                      0.134730
TransUnion           FICO 2                            0.147944
                     FICO 4                            0.190449
                     FICO 5                            0.136819
                     FICO 8                            0.144948
                     FICO 9                            0.131556
                     VantageScore                      0.147597

In [115]:
# just declare the new column within [] and use a formula

data['credit_report_net'] = data['credit_report_good_standing_items'] - data['credit_report_negative_items']
data.head()

,Unnamed: 0,company_reg_number,credit_report_agency,credit_report_date,credit_report_model,credit_report_requests_to_view_last_five_years,credit_report_total_indebtedness,liens_filed_and_open,liens_closed_last_five_years,missed_and_late_payments_last_five_years,filed_court_cases_last_five_years,payment_index,credit_report_negative_items,credit_report_good_standing_items,business_failure_score,credit_report_credit_score,ratio_debt_to_revenue,credit_report_net
0,0,20000000,Experian,2021-11-23,FICO 8,6,7548.00,0,1,0,0,2,1,4,63,765,0.013964,3
1,1,20000001,Equifax,2021-01-29,FICO 8,5,28100.00,0,0,0,0,21,1,1,59,676,0.121491,0
2,2,20000002,Equifax,2021-04-13,FICO 8,6,15631.00,0,1,0,0,16,1,4,53,663,0.076898,3
3,3,20000003,Equifax,2021-09-25,FICO 4,3,0.00,0,0,0,0,2,0,3,93,0,0.000000,3
4,4,20000004,Equifax,2021-08-13,FICO 9,0,75605.28,0,0,0,0,17,0,4,81,773,0.193195,4